.github/workflows/incoming.yml
.github/workflows/main.yaml
.github/workflows/release.yaml
Dockerfile

Node is now 17.0.1
Golang is now 1.17.3

fix: Upgraded container images.

---

go.mod
go.sum
pkg/controller/main_test.go
pkg/internal/testutils/database.go
pkg/metrics/metrics.go

Remove usage of iris builtin stuff.

fix: Changed HTTP testing to use httpexpect.

---

minikube/ingress.yaml
minikube/sentry.yaml
ui/index.tsx
ui/relay/transport.ts
values.my.monetr.dog.yaml

Working on a new sentry transport that will use axios instead of xhr or fetch to send requests. It will also be optimized for monetr's sentry relay server.

fix(sentry)!: Created an axios based Sentry transport.

---

.github/workflows/incoming.yml
.github/workflows/main.yaml
.github/workflows/release.yaml
Makefile
go.sum
scripts/Container.mk

Switching to podman for container builds.

feature: Switching to buildah for container builds.

---

package.json
ui/components/Transactions/TransactionsView/TransactionsView.tsx
ui/components/Transactions/TransactionsView/styles/TransactionsView.scss
ui/shared/transactions/hooks/useFetchTransactions.ts
yarn.lock

feat(ui): Added infinite scrolling to transactions.

---

pkg/repository/security.go

This removes the non-bcrypt login function from the available interface
that is used by the application to authenticate users.

chore(api): Deprecate old login function.

---

Makefile
compose/api-wrapper.sh
compose/monetr.yaml
docker-compose.yaml
pkg/cmd/admin.go
pkg/cmd/kms.go
pkg/config/configuration.go
pkg/platypus/client.go
ui/components/BankAccounts/AllAccountsView/UpdatePlaidAccountDialog.tsx

This adds support for developers to use Google Cloud KMS for local
development instead of the bundled AWS KMS local stack container. This
can be helpful for diagnosing issues with Google specificially. As at
the time of writing this; monetr is hosted on Google Cloud.

feat(dev): Allow Google Cloud KMS for local development.

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml
pkg/controller/controller.go
pkg/controller/main_test.go
pkg/internal/myownsanity/numbers.go
pkg/internal/testutils/log.go
pkg/models/funding_schedule.go
pkg/models/spending.go
pkg/models/spending_test.go
pkg/util/midnight.go
pkg/util/midnight_test.go

This changes how spending contributions are calucated as well as how
spending events are predicted. This should allow for far more precise
funding amounts as well as making sure those amounts are allocated ahead
of time (funding permitting).
fix(testing): Fixed memory leak in http controller tests.
Resolves #937

feat(spending): Significantly improve spending calculations.

---

pkg/controller/plaid.go
pkg/models/spending_test.go
ui/components/BankAccounts/AllAccountsView/UpdatePlaidAccountDialog.tsx
ui/hooks/useAuthentication.ts
ui/views/Setup/InitialPlaidSetup.tsx

This fixes a bug where updating your account selection would not actually add the (new) accounts to your monetr link.
Resolves #1048

fix(plaid): Updated account selections are now reflected.

---

ui/components/BankAccounts/AllAccountsView/UpdatePlaidAccountDialog.tsx

fix(plaid): Fixed failure trying to reauthenticate account.

---

pkg/application/app.go
pkg/controller/middleware.go
pkg/util/forwarded.go

fix(api): Fixed parsing of `X-Forwarded-For`

---

pkg/controller/controller.go
pkg/controller/plaid.go

fix(plaid): Fixed bug with link token caching.

---

ui/components/Expenses/EditFundingScheduleDialog.tsx
ui/components/Expenses/ExpenseDetail.tsx
ui/components/FundingSchedules/FundingScheduleSelectionList.tsx

feat(ui): Added edit expense funding schedule dialog.

---

ui/hooks/bankAccounts.ts
ui/hooks/links.ts

fix(ui): Fixed bug in bank account sink.

---

pkg/controller/controller.go
pkg/util/request.go

fix(cloud): Fixed cloud based request IDs.

---

docker-compose.yaml
pkg/ui/filesystem.go
pkg/ui/no_ui.go

fix(dev): Fixed local dev build failing.

---

ui/components/Spending/TransferDialog.tsx

fix(ui): Fixed transfer dialog crash.

---

ui/components/Expenses/EditExpenseAmountDialog.tsx
ui/components/Goals/EditGoalView.tsx
ui/components/Spending/TransferDialog.tsx

This is being caused by not truncating decimals.
Resolves #1135

fix(ui): Fix rounding issue when updating spending objects.

---

pkg/pubsub/pubsub_test.go

fix(pubsub): Fixed another race condition in pubsub test.

---

tailwind.config.js
ui/components/BankAccounts/AllAccountsView/LinkStatusIndicator.tsx
ui/components/BankAccounts/AllAccountsView/LinkedAccountItem.tsx
ui/components/BankAccounts/AllAccountsView/PlaidLinkStatusIndicator.tsx
ui/hooks/institutions.ts
ui/models/Institution.ts

The institution status indicator will now show transaction update
status, as well as the last sync time. The last sync time has been
removed from the banner for the link though.
Resolves #93

feat(ui): Improve institution status indicator.

---

go.mod
go.sum
pkg/controller/controller.go
pkg/controller/forecast.go
pkg/crumbs/tracing.go
pkg/crumbs/tracing_test.go
pkg/forecast/forecast.go
pkg/forecast/forecast_test.go
pkg/forecast/funding.go
pkg/forecast/funding_test.go
pkg/forecast/spending.go
pkg/forecast/spending_test.go
ui/components/Expenses/CreateExpenseDialog.tsx
ui/components/Recurrence/RecurrenceSelect.tsx
ui/hooks/forecast.ts

feat(forecasting): Building out spending forecasting groundwork.

---

pkg/controller/authentication_test.go
pkg/migrations/schema/2022121200_DeprecateOldPW.tx.up.sql
pkg/models/login.go
pkg/repository/email_test.go
pkg/repository/security.go

Migrate completely to bcrypt for login password encryption.
Resolves #1242

chore(api): Deprecate old password encryption.

---

go.mod
go.sum

Revert "deps(api): update module github.com/getsentry/sentry-go to v0.16.0"

---

ui/components/MButton.tsx
ui/components/MForm.tsx
ui/components/MLink.tsx
ui/components/MTextField.tsx
ui/pages/login-new.tsx
ui/pages/password/forgot-new.stories.tsx
ui/pages/password/forgot-new.tsx
ui/pages/register-new.tsx

This is the new forgot password screen wireframe. It isn't connected to
the actual application yet. But will be soon.
This also includes improvements to all of the form elements that have
been created. Automatically wiring these components up to Formik if the
context exists. This will reduce the number of parameters that need to
be passed to every input when building out forms for monetr.

feat(ui): Building out new forgot password screen.

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml

fix(buidl): Fix github action variable script

---

Chart.yaml
templates/ingress.yaml
templates/service.yaml
values.my.monetr.dog.yaml
values.yaml

This removes support for older ingress resource types as well as
separate service for the ui.
Resolves #1403

fix(helm)!: Fixed ingress resource

---

go.sum
pkg/background/pull_transactions_test.go
pkg/config/configuration.go
pkg/consts/plaid.go
pkg/controller/main_test.go
pkg/controller/plaid_test.go
pkg/internal/mock_plaid/accounts.go
pkg/internal/mock_plaid/link.go
pkg/internal/mock_plaid/mock_exchange.go
pkg/internal/mock_plaid/path.go
pkg/internal/mock_plaid/transactions.go
pkg/internal/mock_plaid/verification.go
pkg/internal/mockgen/platypus.go
pkg/internal/myownsanity/numbers.go
pkg/internal/testutils/plaid.go
pkg/internal/testutils/seed.go
pkg/platypus/account.go
pkg/platypus/account_test.go
pkg/platypus/client.go
pkg/platypus/client_test.go
pkg/platypus/institutions.go
pkg/platypus/platypus.go
pkg/platypus/platypus_test.go
pkg/platypus/sync.go
pkg/platypus/token.go
pkg/platypus/transaction.go
pkg/platypus/webhook.go
pkg/platypus/webhook_test.go

fix(deps): Fixed plaid version update to v3.

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml
.github/workflows/release.yaml
.licensed.yaml
.npmrc
Makefile
compose/ui-entrypoint.sh
docker-compose.yaml
package.json
pnpm-lock.yaml
scripts/Licensed.containerfile

Going forward monetr will use pnpm for package management for its
frontend codebase.

feat(ui): Switching to pnpm over yarn.

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml
Makefile
pkg/controller/funding_schedules_test.go
pkg/controller/spending.go
pkg/controller/spending_test.go

Just writing some tests on the weekend.

chore(test): Writing some more tests.

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml
Makefile
compose/nginx.conf
docker-compose.documentation.yaml
docker-compose.yaml
docs/custom/overrides/partials/tabs.html
docs/developing/documentation.md
mkdocs.yaml

This is going to be breaking out the documentation container workflow
such that it can be run separately from the rest of the local
development workflows.

feat(docs): Improving documentation development workflow.

---

pkg/config/configuration.go
pkg/controller/bank_accounts.go
pkg/controller/config.go
pkg/controller/plaid.go
pkg/internal/fixtures/bank_account.go
pkg/repository/bank_account.go
pkg/repository/repository.go
ui/components/Layout/BudgetingSidebarTitle.tsx
ui/components/Layout/MobileSidebar.tsx
ui/components/MDatePicker.tsx
ui/components/MForm.tsx
ui/components/MSelect.tsx
ui/components/MSelectFrequency.tsx
ui/components/Recurrence/getRecurrencesForDate.ts
ui/hooks/bankAccounts.ts
ui/hooks/institutions.ts
ui/hooks/links.ts
ui/hooks/spending.ts
ui/hooks/store.ts
ui/hooks/useAppConfiguration.ts
ui/hooks/useAuthentication.ts
ui/monetr.tsx
ui/pages/link/create.tsx
ui/pages/setup.tsx
ui/pages/setup/manual.tsx

This is laying the groundwork for adding manual budgeting to monetr.

feat: Adding support for manual budgeting.

---

compose/monetr.yaml
go.mod
server/background/cleanup_jobs.go
server/background/cleanup_jobs_test.go
server/background/jobs.go
server/background/jobs_test.go
server/background/main_test.go
server/background/postgres.go
server/background/postgres_test.go
server/config/configuration.go
server/migrations/schema/2023121500_JobQueue.tx.up.sql
server/models/cron_job.go
server/models/job.go

This provides a new job queue implementation as an alternative to
redis/gocraft. This job queue is designed to be more resistant to
failures like processing a job more than once.

feat(api): Implement PostgreSQL backed job queue.

---

go.mod
go.sum
server/communication/email.go
server/communication/smtp.go
server/communication/smtp_auth.go
server/communication/smtp_auth_local.go

This is a migration to an actual email library to simplify sending emails and hopefully fix several bugs.

fix(api): Fix email sending bugs

---

server/background/sync_plaid.go
server/migrations/schema/2024052700_PlaidCategories.tx.up.sql
server/models/plaid_transaction.go
server/models/transaction.go
server/platypus/transaction.go

This begins the migration away from the legacy plaid category system and
towards the new personal finance categories which are easier to work
with.

feat(plaid): Migrating to personal finance categories

---

server/config/configuration.go
server/controller/routes.go
server/internal/source/contextify_frames.go
server/internal/source/source.go
server/ui/csp.go
server/ui/routes.go

This adds support for reporting CSP violations to Sentry. It also fixes
a bug with the contextify frames pathing for error reporting.
Resolves https://github.com/monetr/monetr/issues/1177

feat(csp): Allowing reporting CSP violations to Sentry.

---

interface/src/components/ArrowLink.tsx
interface/src/components/MDatePicker.tsx
interface/src/components/transactions/ArrowRedirect.tsx
interface/src/components/transactions/SimilarTransactionItem.tsx
interface/src/pages/new/TransactionItem.tsx
interface/src/pages/transaction/details.tsx

Pull request that adds redirection in Similar Transactions. A new small component was created to reuse JSX and logic.

feat(ui): Link similar transactions

---

server/background/sync_plaid.go

This is the first step towards fixing Plaid's syncing mechanism, which
is incorrectly marking accounts in monetr as inactive when it does not
observe them in the Plaid sync response.

fix(plaid): Fixing plaid sync incorrectly marking accounts as inactive

---

interface/src/components/MQueryClient.tsx

Title: Fix: Stabilize QueryClient by Memoizing its Creation
Description:
This PR addresses the issue where the QueryClient was being recreated on every render of the MQueryClient component. By using the useMemo hook, the QueryClient instance is now memoized, ensuring it is only created once and persists across renders. This improves performance and stability, resolving the instability issues previously observed.
Changes:
Memoized the creation of the QueryClient instance in MQueryClient.tsx using the useMemo hook.
Issue Fixed:
Fixes #1841
Testing:
Verified that the QueryClient is not recreated on each render.
Ensured the application behaves correctly and performance is improved.
Notes:
No breaking changes introduced.
Added comments to explain the memoization logic.
Please review the …

Fix unstable QueryClient issue:#1841

---

go.mod
go.sum

Revert "deps(api): update module github.com/getsentry/sentry-go to v0.29.0"

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml
cmake/development.cmake
compose/docker-compose-ngrok.monetr.yaml.in
compose/docker-compose.monetr.yaml.in
compose/docker-compose.vault-kms.yaml.in
compose/mail.nginx.conf.in
compose/nginx.conf.in
compose/ngrok.nginx.conf.in
compose/s3.nginx.conf.in
compose/vault.nginx.conf.in
docs/src/pages/documentation/development/local_development.mdx

Local development now has a dedicated subdomain per service being run,
this will allow monetr to easily add additional services in the future
as needed like flipt for example.

feat(dev): Significantly improve local development

---

.eslintrc.json
interface/package.json
interface/src/components/MDatePicker.tsx
interface/src/components/Switch.tsx
interface/src/components/Tabs.tsx
interface/src/hooks/transactions.ts
interface/src/modals/NewTransactionModal.tsx
interface/src/pages/transactions.tsx
pnpm-lock.yaml
server/controller/spending_test.go
server/controller/transactions.go
server/controller/transactions_test.go

This is to add a modal that would allow users to create transactions
manually without a file import.

feat: Allow transactions to be created via dialog

---

server/background/deactivate_links.go
server/models/plaid_link.go
server/models/plaid_link.strings.go
server/repository/plaid_link.go

There was an issue here where links would not get deactivated
gracefully. I'm trying to resolve it while also improving how it should
work in cleaning up churned user data.

fix(link): Fixed issue where links would not get deactivated gracefully.

---

.github/dictionary.txt
LICENSE
docs/LICENSE.md
docs/package.json
docs/src/components/BackgroundGradientAnimation.tsx
docs/src/components/Hero.tsx
docs/src/components/JoinWaitlist.tsx
docs/src/components/Pricing/PricingCards.tsx
docs/src/components/PricingPage.tsx
docs/src/pages/index.mdx
docs/src/pages/pricing.mdx
docs/src/styles/globals.css
docs/tailwind.config.ts
docs/theme.config.tsx
docs/tsconfig.json
pnpm-lock.yaml

This adds the pricing page to monetr's website. It also makes some (in
my opinion) significant appearance improvements to the landing page and
pricing page.
This also changes monetr to no longer use a BSL license. monetr will
instead be licensed under a far more reasonable [Functional Source
License](https://fsl.software/) for its v1.0.0 release.
With that change it seemed reasonable to also change how the
documentation and landing site are licensed. They are now licensed under
a creative commons license.

feat(docs): Preparing for monetr's launch

---

server/crumbs/crumbs.go
server/round/trip.go

Fixed a nil pointer issue in the round tripper observability code.
Resolves #2006

fix(sentry): Fixing round tripper observability implementation

---

interface/src/components/Combobox.tsx
interface/src/components/Layout/BudgetingSidebarTitle.tsx
interface/src/components/setup/manual/ManualLinkSetupIncome.tsx
interface/src/hooks/bankAccounts.ts
interface/src/modals/NewBankAccountModal.spec.tsx
interface/src/modals/NewBankAccountModal.tsx
server/controller/bank_accounts.go
server/controller/bank_accounts_test.go
server/repository/bank_account.go

This is adding support for people to create additional manually
budgeted bank accounts on the same manual link.

feat(manual): Adding support for additional manual accounts on one link

---

.github/workflows/incoming.yaml
.github/workflows/main.yaml
go.mod
go.sum
server/background/process_ofx_upload.go
server/currency/CMakeLists.txt
server/currency/currency.go
server/currency/currency_test.go
server/internal/calc/cents.go

This is a library that I wrote to access the host system's locale
information. monetr uses this to get basic information about what
locales are valid and now information about what fractional digits a
currency should have.

deps(api): Bumping the locale go dependency

---

server/migrations/schema/2025011701_LongerClusters.tx.up.sql

fix(txn): Fixed transaction clusters for large names

---

go.mod
interface/src/components/Combobox.tsx
interface/src/components/Command.tsx
interface/src/components/Layout/BudgetingSidebarTitle.tsx
interface/src/components/Layout/MobileSidebar.tsx
interface/src/components/Layout/SelectBankAccount.tsx
interface/src/components/MTopNavigation.tsx
interface/src/components/SelectCurrency.tsx
interface/src/hooks/bankAccounts.ts
interface/src/hooks/useInstalledCurrencies.spec.ts
interface/src/hooks/useInstalledCurrencies.ts
interface/src/modals/NewBankAccountModal.tsx
interface/src/monetr.tsx
interface/src/pages/bank/settings.tsx
interface/src/pages/transaction/details.tsx
interface/src/testutils/hooks.tsx
server/controller/bank_accounts.go
server/controller/bank_accounts_test.go
server/controller/currency.go
server/controller/routes.go
server/currency/golang_test.go

This is the last piece needed for someone to actually customize the
currency of a manual bank account in monetr.
This will also include some quality of life changes around the bank
account picker, including moving the "Add account" button into the
actual bank account list which seems to make more sense.
Resolves #2330

feat(ui): Allow currency of bank account to be changed

---

docs/package.json
interface/package.json
pnpm-lock.yaml

Revert "deps(ui): update dependency lucide-react to v0.475.0 - autoclosed"

---

docs/src/pages/documentation/configure/postgres.mdx
server/cmd/admin.go
server/cmd/beta.go
server/cmd/cleanup_jobs.go
server/cmd/develop.go
server/cmd/jobs.go
server/cmd/migrate.go
server/cmd/serve.go
server/config/configuration.go
server/database/CMakeLists.txt
server/database/database.go
server/database/database_test.go
server/internal/myownsanity/strings.go
server/internal/testutils/database.go

This code is extremely old and kind of messy, this is just refactoring
it to make some improvements as well as to make documentation better.

fix(database): Refactoring some of the database entrypoint code

---

server/background/notification_trial_expiry.go
server/background/notification_trial_expiry_test.go

fix(job): Fixing trial notification expiry
