Makefile
scripts/Container.mk

GitHub actions will no longer attempt to build linux/arm64 container images for the time being. There is an issue right now (see issue #530) where libc is causing some problems with the build.
Until I can resolve the build issues, this will fix the build pipelines for now.

fix(temp): Removed `linux/arm64` containers from builds

---

pkg/billing/easy.go
pkg/billing/paywall.go
pkg/billing/paywall_test.go
pkg/billing/stripe.go
pkg/cache/wrapper_test.go
pkg/controller/billing.go
pkg/controller/billing_test.go
pkg/controller/user.go
pkg/internal/fixtures/login.go
pkg/internal/testutils/redis.go
pkg/migrations/schema/2022022500_SubscriptionStatus.tx.down.sql
pkg/migrations/schema/2022022500_SubscriptionStatus.tx.up.sql
pkg/models/account.go
ui/shared/authentication/actions.ts
ui/shared/authentication/actions/bootstrapLogin.ts
ui/shared/authentication/selectors.ts
ui/shared/authentication/state.ts
ui/views/Subscriptions/Subscribe.tsx

When a subscription is "past_due", right now it is possible for another
subscription to be made. With the updated payment method; both
subscriptions can then charge the customer. This is an attempt to
resolve that by preventing a new subscription from being made unless the
original subscription is truely canceled or expired.
Resolves #717

fix: Prevent multiple subscriptions from being made.

---

docs/stylesheets/extra.css

Made tables describing objects and fields easier to read by making sure
the field name does not wrap.
Resolves #974

fix(docs): Fixed table rendering in documentation.

---

ui/hooks/transactions.ts

Make sure the array of transactions returned by the hook is never
undefined. It should at least be an empty array in any code path.
Resolves #1032

fix(ui): Fix transactions page crash.

---

docs/developing/api/resources/authentication.md
pkg/controller/authentication.go
pkg/controller/authentication_test.go
pkg/controller/controller.go
pkg/controller/error.go
pkg/controller/errors.go
pkg/controller/plaid_test.go
pkg/controller/user_test.go
pkg/repository/unauthenticated.go

fix(api): Don't return internal errors to the client.

---

pkg/models/funding_schedule_test.go
pkg/util/midnight.go
pkg/util/midnight_test.go

It was not caluclating the relative midnight for a funding schedule
when calculating the next occurrence.
Resolves #1064

fix(funding): Fixed funding schedule calculation.

---

docs/custom/overrides/partials/tabs.html

fix(docs): Fixed sign in URL on the documentation site.

---

go.mod
pkg/models/funding_schedule.go
pkg/models/spending_test.go

Fixed issue where when the next recurrence or the due date of a spending
object matched the funding date, it would omit that funding event from
its calculations.
Resolves #1077

fix(spending): Fix spending contribution calculation.

---

ui/components/Authentication/Registration/RegisterView.tsx
ui/hooks/useSignUp.ts

If you attempt to sign up using an invalid beta code you will be
presented with a Sentry dialog. This is not correct and is removed in
this commit. This is not a page crash and should not behave like that.

fix(ui): Fixed Sentry crash dialog during registration.

---

pkg/controller/icons.go
ui/Root.tsx
ui/hooks/useIconSearch.ts

This will make it so that the transaction names no longer show up in the
request URL in load balancer logs.
Resolves #1175

feat(ui): Allow icons to be searched via POST request.

---

ui/components/FundingSchedules/FundingScheduleListItem.tsx

The funding schedule page would crash if it was the first page loaded,
this was because the page did not properly wait for balances to load
before trying to access the balance data.
Resolves #1244

fix(ui): Fixed crash on the funding schedule page.

---

pkg/controller/icons.go

This removes support for `GET` requests against the icon search
endpoint. Going forward, requests must be made via a `POST` request in
order to keep transaction data out of query parameters.
Resolves #1217

fix(api): Deprecate old icon search endpoint.

---

pkg/forecast/forecast_test.go
pkg/forecast/funding.go
pkg/forecast/spending.go

The forecasting code will now respect the deadlines specified in the
context passed to them. This will make sure that we don't end up with
runaway code in the forecasting loop.
Related to #1243

fix(api): Add proper timeout handling in forecasting.

---

pkg/migrations/schema/2023022000_DateStarted.tx.up.sql
pkg/models/funding_schedule.go
pkg/models/spending.go
pkg/repository/expenses.go
pkg/repository/funding_schedules.go

Right now we do not store the DTSTART component of the RRule, this has
led to some bugs already where we have to assume the DTSTART based on
some educated guess data. This can lead to wrong calculations in the
future. So going forward I want to support this parameter. This is the
start of the work on that.

feat(api): Add DTSTART equivalent support to spending/funding.

---

ui/components/Transactions/TransactionsView/TransactionsView.tsx
ui/hooks/transactions.ts

Previously if you had a number of transactions exactly divisible by 25
we would continue to request more and more transactions unnecessarily.
This makes it so that we properly handle this by looking to see if we
have any pages with less than 25, which would include a page that is
empty.
Resolves #1331

fix(ui): Fixed requesting more transactions.

---

pkg/controller/plaid.go

When we would initiate a sync after a Plaid update callback had been
completed, we were always triggering a pull transactions sync. This is
the legacy method for syncing data, and the preferred method is the
regular plaid sync.
This resolve the issue by looking at the setting on the plaid link
itself to determine which type of sync to initiate.
Resolves #1445

fix(plaid): Fixed an issue with Plaid update callback syncing.

---

Makefile

When running `make develop` for the first time, I ran into an error where a `install` binary was being called.
This happens because I didn't have `pnpm` installed, resulting in `$(PNPM) install` resolving to ` install` 
```
$ make develop
install
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
[-o owner] file1 file2
install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
[-o owner] file1 ... fileN directory
install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [/Users/fbittenc/go/src/github.com/monetr/monetr/node_modules] Error 64
```
I've added a check for `pnpm` in Makefile to show a proper error message when running `make develop` without `pnpm`, resulting in the following message:
```
$ make develop
Error: pnpm not found.
make: *** …
```

fix(makefile): Add check for pnpm

---

pkg/repository/plaid_link.go

This makes it so that the sync data is also cleaned up as part of the
removal of the link data necessary to communicate with Plaid.
Resolves #1497

fix(plaid): Fixed deactivate Plaid link from lapsed subscription.

---

package.json
pnpm-lock.yaml
postcss.config.cjs

I had at some point removed autoprefixer apparently, which auto fills a
ton of CSS stuff for various browsers. This caused the compiled CSS file
to not have anything for webkit, including blur stuff. So the browser on
mobile was just showing the menu without any of the fancier styling.
Resolves #1513

fix(ui): Fixed mobile menu not displaying properly on iOS.

---

ui/pages/transaction/details.tsx

The spent from dropdown should not show on the details screen for
deposit transactions.
Resolves #1512

fix(ui): Don't show spending selection on deposits.

---

ui/hooks/bankAccounts.ts
ui/monetr.tsx
ui/util/sortAccounts.spec.ts
ui/util/sortAccounts.ts

This fixes the order in which accounts will be displayed in the
budgeting sidebar dropdown.
Resolves #1511

fix(ui): Fixed account sorting.

---

ui/components/MSelectSpending.tsx
ui/components/MSelectSpendingTransaction.tsx
ui/modals/NewGoalModal.tsx
ui/modals/TransferModal.tsx
ui/models/Balance.ts
ui/models/BankAccount.ts
ui/models/Spending.ts
ui/models/Transaction.ts
ui/pages/expense/ExpenseTimeline.tsx
ui/pages/expense/details.tsx
ui/pages/funding/details.tsx
ui/pages/goals/details.tsx
ui/pages/new/FundingItem.tsx
ui/pages/transaction/details.tsx
ui/util/amounts.spec.ts
ui/util/amounts.ts
ui/util/formatAmount.spec.ts
ui/util/formatAmount.ts

This fixes the funding schedule details page amount formatting, as well
as every other place where amounts might be formatted. This makes it so
that every time a number is formatted it is done so using a common
function. This will also help support other currency codes in the
future.
Resolves #1509

fix(ui): Fixed amount formatting in the UI.

---

pkg/forecast/fixtures/elliots-result-20230705.json
pkg/forecast/forecast_test.go
pkg/forecast/spending.go

Fix an issue where the forecasting code would not recognize that the
goal is complete and would assume that contributions needed to be made
to it equal to the `targetAmount - currentAmount`. This isn't correct
because goals have a used amount that keeps track of funds spent from
the goal. This makes it so the used amount is now taken into account for
contributions predicted.
Resolves #1561

fix(forecast): Fixed bug with forecasting completed goals

---

server/cmd/admin.go
server/internal/mockgen/key_management.go
server/repository/secrets.go
server/repository/secrets_test.go
server/secrets/aws_kms.go
server/secrets/google_kms.go
server/secrets/google_kms_test.go
server/secrets/key_management.go
server/secrets/plaintext.go

Plaintext secrets were meant to be stored as exclusively plain text. But
the changes to how secrets were stored is causing them to be
read/written as hexadecimal which is incorrect. This lives the
hexadecimal encoding out of the secrets repository and instead into the
key management implementation itself. If the implementation is actually
encrypting the secrets then they will be returned in a hexadecimal
format. Plaintext secrets will be stored unaltered.
Resolves #1673

fix(api): Fix plain text secret encoding.

---

server/background/postgres.go
server/migrations/schema/2024021901_JobRetries.tx.up.sql
server/models/job.go

This is laying the ground work for allowing the PostgreSQL job processor
to handle retrying a job. This will be done by marking the initial job
as failed and creating a new job row with a new signature and
incrementing the attempt counter.

feat(jobs): Adding basic support for job retries

---

server/background/sync_teller.go
server/migrations/schema/2024022100_FixCreditTransactions.tx.up.sql
server/models/teller_bank_account.go

Transaction amounts were inverted for transactions on credit accounts.
This corrects the transactions but does not correct the balance of those
accounts.
Resolves #1677

fix(teller): Fix teller transaction amounts on credit accounts.

---

compose/docker-compose.monetr.yaml.in
compose/monetr.yaml
server/application/app_test.go
server/cmd/serve.go
server/config/configuration.go
server/config/server.go
server/controller/authentication.go
server/controller/billing.go
server/controller/communication_helpers.go
server/controller/errors.go
server/controller/main_test.go
server/controller/routes.go
server/controller/user.go
templates/config.yaml
values.my.monetr.app.yaml
values.my.monetr.dev.yaml
values.yaml

Previously monetr would rely on 3 fields to determine the external URL
and protocol used to access the application. This was confusing and was
inconsistent throughout the application.
This transitions monetr to using a single setting,
`$.server.externalUrl` which is a simple URL. monetr then parses this
URL and derives the protocol, hostname, and path prefix if there is one.
URLs for monetr are then built based on this base URL.
Resolves #1800

fix(config): Fixed how the external URL and protocol was determined

---

go.mod
go.sum
server/application/app_test.go
server/background/sync_plaid.go
server/background/sync_plaid_test.go
server/config/configuration.go
server/consts/plaid.go
server/controller/main_test.go
server/controller/plaid_test.go
server/internal/mock_plaid/accounts.go
server/internal/mock_plaid/link.go
server/internal/mock_plaid/mock_exchange.go
server/internal/mock_plaid/path.go
server/internal/mock_plaid/transactions.go
server/internal/mock_plaid/verification.go
server/internal/mockgen/platypus.go
server/internal/testutils/plaid.go
server/platypus/account.go
server/platypus/account_test.go
server/platypus/client.go
server/platypus/client_test.go
server/platypus/institutions.go
server/platypus/platypus.go
server/platypus/platypus_test.go
server/platypus/sync.go
server/platypus/token.go
server/platypus/transaction.go
server/platypus/webhook.go
server/platypus/webhook_test.go

The Plaid sync functionality no longer makes an additional API call to
the bank account endpoint. Instead it relies on the accounts returned
from the sync API call itself.
Resolves #1809

fix(plaid): Reduce number of Plaid API calls necessary for syncing

---

CMakePresets.json
cmake/development.cmake
compose/docker-compose.monetr.yaml.in
compose/docker-compose.s3-storage.yaml.in
compose/monetr.yaml
compose/nginx.conf
server/cmd/storage.go
server/config/configuration.go
server/controller/main_test.go
server/storage/filesystem.go
server/storage/filesystem_test.go

The filesystem storage provider now provides better validation for the
provided base path. Requiring that the path is an absolute path and that
the process has permissions to access the directory.
This also adds MONETR_STORAGE_PROVIDER to the cmake configuration,
allowing the storage provider to be customized between S3 and the
filesystem provider.
Resolves #1798

fix(storage): Improved path validation in filesystem storage provider

---

server/controller/forecast.go
server/forecast/forecast.go
server/forecast/forecast_test.go
server/forecast/funding.go
server/forecast/funding_test.go
server/forecast/spending.go
server/forecast/spending_test.go

This code previously would just panic if there was a problem, which
sucked because it did handle timeouts. So if it did timeout it would
simply panic which was not helpful.
This corrects all of the interfaces such that they now properly return
an error to the caller when there is a timeout or other problem.
Resolves #1793

fix(forecast): Make the forecasting code return a proper error

---

interface/src/pages/new/TransactionItem.tsx

This just adds back the on click handler to the overlay. But long term
this should still be improved overall.
Related to: #1829

fix(ui): Fixed mobile transactions items not be clickable

---

server/cmd/admin.go

monetr is moving away from GCP and instead moving to a co-located
datacenter. To that end, we need to migrate all of the data encrypted
using Google Cloud's KMS, to our new KMS system backed by Hashicorp
Vault.
This lays the groundwork of an admin function to do exactly that.

feat(cmd): Adding admin command to migrate between KMS providers

---

server/controller/main_test.go
server/internal/testutils/http.go
server/ui/routes.go

Github's security thing is complaining about using a raw path from the
user's input to load files. But there really is no risk because the
filesystem that the UI is loaded from is embeded and is basically
sandboxed. There are no extra files that could possibly be requested
maliciously.
But I'm going to try to improve it anyway to keep the alert from comming
up again and again.

fix(ui): Fixing uncontrolled path bug in UI router

---

server/background/jobs.go
server/background/sync_plaid_accounts.go
server/background/sync_plaid_accounts_test.go
server/migrations/schema/2024100700_PlaidAccountSync.tx.up.sql
server/models/plaid_link.go
server/platypus/client.go

Periodically sync bank accounts to find out which ones are no longer
active in Plaid.
Resolves #1830

feat(api): Correctly mark accounts as inactive via Plaid.

---

Makefile
compose/docker-compose.monetr.yaml.in
compose/nginx-cloud.conf
compose/nginx.conf
docs/src/pages/documentation/development/local_development.mdx
interface/CMakeLists.txt
interface/package.json
interface/rspack.config.js

The "lite" development environment allows developers to only work on the
frontend of monetr but still use a real API backend without needing to
run the entire stack locally. This development environment proxies API
requests upstream to a specified API server such as the staging
environment.
This allows for bugs to be reproduced more easily or for changes to be
made on systems that may not want or need to run all of the extra
servives necessary.

feat(dev): Adding local development "lite" environment

---

interface/src/hooks/useAuthentication.ts
interface/src/monetr.tsx
interface/src/pages/settings/CMakeLists.txt
interface/src/pages/settings/billing.spec.tsx
interface/src/pages/settings/billing.tsx
server/background/notification_trial_expiry.go
server/background/notification_trial_expiry_test.go
server/billing/checkout.go
server/controller/billing.go
server/controller/billing_test.go
server/models/account.go

If someone wants to subscribe to monetr before their trial has ended
they will now be able to do so. This will not trample the trial data,
but will make the subscription status take priority. It also makes sure
that we don't send trial expiry notifications when we don't need to.

feat(billing): Allow users to subscribe before their trial ends

---

interface/src/components/Layout/BudgetingSidebar.tsx
interface/src/components/expenses/ExpenseItem.tsx
interface/src/components/goals/GoalItem.tsx
interface/src/components/transactions/TransactionItem.tsx
interface/src/models/Balance.ts
interface/src/models/BankAccount.ts
interface/src/models/Spending.ts
interface/src/models/Transaction.ts
interface/src/pages/register.tsx
interface/src/util/amounts.spec.ts
interface/src/util/amounts.ts
server/consts/currency.go
server/controller/plaid.go
server/migrations/schema/2025011300_BankCurrency.tx.up.sql
server/models/bank_account.go
server/models/plaid_bank_account.go
server/platypus/account.go
server/repository/balances.go

This is just some tweaks throughout the app for how we are formatting
currencies. ATM monetr officially only supports USD, but with these
changes its no longer that far off from being able to support whatever
currency someone wants.

fix(locale): Improving currency formatting on the frontend

---

server/migrations/schema/2025011700_LongerTransactions.tx.up.sql

I had limited data to only being 200 characters long, but some
transaction memo's from Plaid can be over 200 characters so I'm bumping
the limit to 300 instead. Maybe I should just use TEXT?
Resolves #2324

fix(plaid): Allow for larger transactions from Plaid

---

server/controller/authentication.go
server/controller/authentication_test.go

I had assumed that locale codes from browsers would match the format
that I was using on the server side, but it seems that is not always the
case. So I've changed the code to fall back to a known good default for
the mean time.
Resolves #2335

fix(locale): Don't prevent sign ups for uknown locales

---

interface/src/hooks/useLocaleCurrency.spec.ts
interface/src/hooks/useLocaleCurrency.ts

We should never have an undefined currency returned from the
useLocaleCurrency hook.
Resolves #2336

fix(ui): Fixing undefined currency

---

docs/CMakeLists.txt

The cmake tests for documentation were incorrectly appening the flags.
Resolves #2351

fix(test): Fix documentation tests in CI

---

go.mod
go.sum
server/cmd/version.go
server/internal/calc/euclidean_amd64.go
server/internal/calc/euclidean_amd64_test.go
server/internal/calc/vector_amd64.go
server/internal/calc/vector_amd64_test.go

Instead of using the CPUID package, use the x/sys/cpu package provided
by golang's authors. This package was already being used anyway so this
change also removes a dependency and doesn't technically add one.
Resolves #2332

fix(api): Detect AVX and AVX512F instruction sets using runtime

---

server/formats/ofx/parse.go
server/formats/ofx/parse_test.go

User has a slightly different date format in their OFX file, monetr was
being too strict about the format so it wasn't parsing it. This makes it
a bit more flexible. But if there are more date formats that I haven't
seen yet then there will still be bug reports in the future.
Resolves #2362

fix(ofx): Allow an alternative OFX date format to be parsed

---

interface/src/pages/register.tsx
server/controller/authentication.go
server/controller/authentication_test.go

If a password is provided that is longer than 72 bytes then bcrypt wont
be able to handle it. This might be another indicator to start looking
into argon2 instead, but idk what it's limitations are.
In the mean time, return a proper error for this situation as well as
validate the input on the frontend.
Resolves #2367

fix(api): Fix not handling long passwords

---

server/migrations/schema/2025020900_ClusterConsistency.tx.up.sql
server/models/transaction_cluster.go
server/recurring/dbscan_test.go
server/recurring/recurring.go
server/recurring/recurring_test.go
server/recurring/similar.go
server/recurring/similar_test.go
server/recurring/tfidf.go

This work definitly hurts the efficiency of the transaction cluster
calculation, I think I can improve some of that later on. But in the
mean time this should provide a really good starting point for providing
consistent identifiers for transaction clusters. Specifically, the
cluster calculation now generates a signature based on the top 5 most
valuable words in the cluster that have a value greater than 0. This way
words that push the clusters closer together will end up making up the
signature. The most valuable words of those should be consistent. I
might need to reduce the number of words to consider down to something
like 2 though.

feat(api): Improving transaction similarity API experience

---

server/migrations/schema/2025021700_DropBalanceView.tx.up.sql

This view has been unused since the v1.3.0 release, but to make sure
that API requests didn't fail during the rollout of the release, the
view was not dropped in the same version. This change drops the view for
the new version of monetr.

fix(api): Removed unused balances view

---

server/background/sync_plaid.go
server/internal/mock_http_helper/responder.go
server/internal/mock_plaid/sync.go
server/platypus/error.go
server/platypus/platypus.go
server/platypus/sync_test.go

When we get an error from Plaid indicating that the sync must be retried
from scratch we now throw an error causing the transaction to be rolled
back. We then retry the job from scratch up to a few attempts to correct
the issue. If we get any other error then we still return it normally.
Resolves #2453

fix(plaid): Fix Plaid pagination error handling

---

server/background/calculate_transaction_clusters.go
server/recurring/recurring_test.go
server/recurring/similar.go
server/recurring/similar_test.go

It was possible for transaction clusters to be calculated without a
name, this should be considered a bug but until I've had more time to
investigate it I'm just going to omit clusters without a name from being
persisted to the database.
What is likely happening is this "no name" cluster is a bunch of
transactions that are so close to the 0 point, or consisting of such low
value words in their description that there aren't any non-zero words to
use for a name.
Resolves #2475

fix(api): Fixed transaction clusters not having a name

---

cmake/NodeModules.cmake
interface/src/components/Layout/BalanceFreeToUseAmount.tsx
interface/src/components/Layout/BankSidebar.tsx
interface/src/components/Layout/BudgetingSidebar.tsx
interface/src/components/MTopNavigation.tsx
interface/src/components/Switch.tsx
interface/src/components/transactions/RemoveTransactionButton.tsx
interface/src/components/transactions/SimilarTransactionItem.tsx
interface/src/hooks/transactions.ts
interface/src/modals/RemoveTransactionModal.tsx
interface/src/modals/TransferModal.tsx
interface/src/pages/expense/details.tsx
interface/src/pages/funding/details.tsx
interface/src/pages/goals.tsx
interface/src/pages/goals/details.tsx
interface/src/pages/transaction/details.tsx
interface/src/pages/transactions.tsx
tailwind.config.ts

If you are working with a manual budget, you will now be able to remove
transactions from that budget. Navigating to the transaction details
page and clicking remove will show a confirmation modal, prompting you
whether or not removing the transaction will affect balances.
Resolves #2542

feat(ui): Adding UX to remove transactions for manual links

---

.eslintrc.json
interface/package.json
interface/src/components/MDatePicker.tsx
interface/src/components/MSelectFrequency.tsx
interface/src/components/Recurrence/getRecurrencesForDate.ts
interface/src/components/setup/manual/ManualLinkSetupIncome.tsx
interface/src/hooks/useTimezone.ts
interface/src/modals/NewExpenseModal.tsx
interface/src/modals/NewFundingModal.tsx
interface/src/modals/NewGoalModal.tsx
interface/src/modals/NewTransactionModal.tsx
interface/src/pages/transaction/details.tsx
pnpm-lock.yaml

If a user has their timezone configured as X and their browser timezone
is Y. This can cause some of the dates sent to the server to be
malformed and can cause some odd behaviors. For lack of a better
solution for now (like not having times at all and instead only using
dates?); this adds timezone to components that need it. Forcing the time
to be shown and calculated in the user's timezone instead of only the
browsers timezone.
Resolves #2386

fix(ui): Use account timezone if available instead of browser timezone

---

server/background/process_ofx_upload.go
server/formats/ofx/parse.go
server/formats/ofx/parse_test.go
server/internal/myownsanity/numbers.go

OFX files should respect the debit/credit for direction when available.
Resolves #2687

fix(ofx): Fixing sometimes inverted OFX amounts

---

server/internal/calc/euclidean_amd64.go
server/internal/calc/euclidean_amd64.s
server/internal/calc/vector_amd64.s

Instead of using two instructions to do a square and then an add to the
accumulator register. I've combined them into a single instrction
VFMADD231PS or VFMADD231PD. I still need to benchmark to make sure these
are faster. But the code is now simpler

feat(api): Improve similarity caluclations
